language: android
android:
  components:
    - addon-google_apis-google-30
    - extra-android-support

# Avoid double build on PRs - it does a pre-merge to master and then builds that
branches:
  only:
    - "master"

script: script: cd androiw && ./gradlew build
